### ISSUE TITLE
[BUG] Comando "Bot" é adicionado automaticamente pelo Telegram

### ISSUE THREAD

**Issue by jacksonpradolima** [thiagodnf/cardapio-ru-bot#1]
Olá,
Ao informar algum comando do bot, por exemplo, ```/ruhoje```, o Telegram adiciona automaticamente ```@CardapioRUBot```. Entretanto, o comando ```/ruhoje@CardapioRUBot``` não é aceito/válido, sendo apenas válido para o Bot o comando ```/ruhoje```.

**Comment by thiagodnf** [comment]
Olá @jacksonpradolima  

Obrigado pelo feedback. A versão 1.2.0 corrigiu o problema
