### ISSUE TITLE
[BUG] Comandos retornam "Ooops! Usuário não reconhecido" em conversa particular com o bot.

### ISSUE THREAD

**Issue by rhrlima** [thiagodnf/cardapio-ru-bot#2]
Em uma conversa particular com o bot todos os comandos com exceção do /help retornam a mensagem "Ooops! Usuário não reconhecido".

**Comment by thiagodnf** [comment]
Olá @rhrlima 

Obrigado pelo feedback. A versão 1.2.0 corrigiu o problema
